apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 9.4.1
    chart: kube-prometheus-stack
    helm:
      values: |
        prometheus:
          prometheusSpec:
            retention: 30d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 16Gi
          additionalServiceMonitors:
            - name: argocd-metrics
              selector:
                matchLabels:
                  app.kubernetes.io/name: argocd-metrics
              namespaceSelector:
                matchNames: ["argocd"]
              endpoints:
                - port: metrics
            - name: argocd-server-metrics
              selector:
                matchLabels:
                  app.kubernetes.io/name: argocd-server-metrics
              namespaceSelector:
                matchNames: ["argocd"]
              endpoints:
                - port: metrics
            - name: argocd-repo-server-metrics
              selector:
                matchLabels:
                  app.kubernetes.io/name: argocd-repo-server-metrics
              namespaceSelector:
                matchNames: ["argocd"]
              endpoints:
                - port: metrics
        grafana:
          service:
            type: NodePort
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
